name: Arduino Library specification
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:
jobs:
  ArduinoLibrarySpecificationCheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
